[package]
name = "yassy"
version = "0.1.0"
authors = ["stefan"]

[dependencies]
libc = "*"

[lib]
name = "yassy"
crate-type = ["dylib"] # ?

[dev-dependencies] # for testing/documentation
GSL = "*"
gnuplot = "*"
getopts = "=0.2.14" # gnuplot dependency
